In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#import seaborn as sns

In [2]:
dados1 = 'reservas.csv'
#leitura csv reservas

In [3]:
dados2 = 'hospedes.csv'
#leitura csv quartos

In [4]:
dados3 = 'quartos.csv'
#leitura csv hoteis

In [5]:
dados4 = 'hoteis.csv'
#leitura csv hospedes

In [6]:
dados5 = 'avaliacoes.csv'
#leitura csv avaliacoes

In [7]:
dados6 = 'avaliacoes_2025.csv'

In [8]:
dados7 = 'reservas_2025.csv'

In [9]:
df_reservas = pd.read_csv(dados1, sep=',')
df_hospedes = pd.read_csv(dados2, sep=',')
df_quartos = pd.read_csv(dados3, sep=',')
df_hoteis = pd.read_csv(dados4, sep=',')
df_avaliacoes = pd.read_csv(dados5, sep=',')
df_avaliacoes_25 = pd.read_csv(dados6, sep=',')
df_reservas_25 = pd.read_csv(dados7, sep=',')

In [10]:
df_reservas_total = pd.concat([df_reservas, df_reservas_25], ignore_index=True)
df_reservas_total.dtypes

id_reserva          int64
id_hospede          int64
id_quarto             str
id_hotel            int64
data_checkin          str
data_checkout         str
canal_reserva         str
valor_diaria      float64
status_reserva        str
data_reserva          str
dtype: object

In [72]:
df_quartos

,id_quarto,id_hotel,tipo_quarto,capacidade,valor_base,andar,vista
0,Q001,1,Standard,2,320.0,1,Jardim
1,Q002,1,Standard,2,320.0,2,Jardim
2,Q003,1,Standard,2,320.0,3,Jardim
3,Q004,1,Standard,2,320.0,4,Jardim
4,Q005,1,Superior,3,480.0,5,Mar
5,Q006,1,Superior,3,480.0,6,Mar
6,Q007,1,Superior,3,480.0,7,Mar
7,Q008,1,Luxo,4,750.0,8,Mar
8,Q009,1,Luxo,4,750.0,9,Mar
9,Q010,1,Suite,5,1200.0,10,Panorâmica
10,Q011,1,Suite,5,1200.0,11,Panorâmica
11,Q012,1,Suite master,6,2200.0,12,Panorâmica
12,Q013,2,Standard,2,280.0,1,Jardim
13,Q014,2,Standard,2,280.0,2,Jardim
14,Q015,2,Standard,2,280.0,3,Jardim
15,Q016,2,Superior,3,420.0,4,Piscina
16,Q017,2,Superior,3,420.0,5,Piscina
17,Q018,2,Superior,3,420.0,6,Piscina
18,Q019,2,Luxo,4,680.0,7,Mar
19,Q020,2,Luxo,4,680.0,8,Mar
20,Q021,2,Suite,5,1100.0,9,Panorâmica
21,Q022,2,Suite,5,1100.0,10,Panorâmica
22,Q023,2,Suite master,6,1950.0,11,Panorâmica
23,Q024,3,Standard,2,260.0,1,Jardim
24,Q025,3,Standard,2,260.0,2,Jardim
25,Q026,3,Standard,2,260.0,3,Jardim
26,Q027,3,Superior,3,400.0,4,Piscina
27,Q028,3,Superior,3,400.0,5,Piscina
28,Q029,3,Superior,3,400.0,6,Piscina
29,Q030,3,Luxo,4,640.0,7,Mar
30,Q031,3,Luxo,4,640.0,8,Mar
31,Q032,3,Suite,5,1050.0,9,Panorâmica
32,Q033,3,Suite,5,1050.0,10,Panorâmica
33,Q034,3,Suite master,6,1900.0,11,Panorâmica
34,Q035,4,Standard,2,350.0,1,Cidade
35,Q036,4,Standard,2,350.0,2,Cidade
36,Q037,4,Standard,2,350.0,3,Cidade
37,Q038,4,Standard,2,350.0,4,Cidade
38,Q039,4,Superior,3,520.0,5,Cidade
39,Q040,4,Superior,3,520.0,6,Cidade
40,Q041,4,Luxo,4,820.0,7,Mar
41,Q042,4,Luxo,4,820.0,8,Mar
42,Q043,4,Suite,5,1350.0,9,Panorâmica
43,Q044,4,Suite master,6,2500.0,10,Panorâmica
44,Q045,5,Standard,2,420.0,1,Cidade
45,Q046,5,Standard,2,420.0,2,Cidade
46,Q047,5,Standard,2,420.0,3,Cidade
47,Q048,5,Standard,2,420.0,4,Cidade
48,Q049,5,Superior,3,620.0,5,Cidade
49,Q050,5,Superior,3,620.0,6,Cidade
50,Q051,5,Superior,3,620.0,7,Cidade
51,Q052,5,Luxo,4,950.0,8,Cidade
52,Q053,5,Luxo,4,950.0,9,Cidade
53,Q054,5,Luxo,4,950.0,10,Cidade
54,Q055,5,Suite,5,1600.0,11,Panorâmica
55,Q056,5,Suite,5,1600.0,12,Panorâmica
56,Q057,5,Suite master,6,2800.0,15,Panorâmica
57,Q058,9,Standard,2,300.0,1,Jardim

In [11]:
df_avaliacoes_total = pd.concat([df_avaliacoes, df_avaliacoes_25], ignore_index=True)
df_avaliacoes_total.dtypes

id_avaliacao              int64
id_reserva                int64
nota_geral               object
nota_limpeza            float64
nota_atendimento         object
nota_custo_beneficio     object
comentario                  str
data_avaliacao              str
dtype: object

In [12]:
df_hoteis.dtypes

id_hotel        int64
nome_hotel        str
cidade            str
estado            str
categoria         str
n_quartos     float64
dtype: object

In [61]:
#atribuindo 5 estrelas para o hotel em SP
df_hoteis['categoria'] = df_hoteis['categoria'].str.replace('6 estrelas', '5 estrelas')
df_hoteis

   id_hotel           nome_hotel          cidade estado   categoria  n_quartos
0         1       Nara Fortaleza       Fortaleza     CE  5 estrelas        120
1         2          Nara Recife          Recife     PE  4 estrelas         95
2         3        Nara Salvador        Salvador     BA  4 estrelas        100
3         4  Nara Rio de Janeiro  Rio de Janeiro     RJ  3 estrelas         80
4         5       Nara São Paulo       São Paulo     SP  5 estrelas        150

In [ ]:
#atribuindo a mediana 100 quartos para Salvador
#alterando tipo de dado de float para int
df_hoteis['n_quartos'] = df_hoteis['n_quartos'].fillna(110.0).astype(int)

   id_hotel           nome_hotel          cidade estado   categoria  n_quartos
0         1       Nara Fortaleza       Fortaleza     CE  5 estrelas        120
1         2          Nara Recife          Recife     PE  4 estrelas         95
2         3        Nara Salvador        Salvador     BA  4 estrelas        100
3         4  Nara Rio de Janeiro  Rio de Janeiro     RJ  3 estrelas         80
4         5       Nara São Paulo       São Paulo     SP  5 estrelas        150

In [15]:
#transformando Rio De Janeiro em Rio de Janeiro
df_hoteis['cidade'] = df_hoteis['cidade'].str.replace('De', 'de')
df_hoteis['cidade'] = df_hoteis['cidade'].str.replace('Sao', 'São')
df_hoteis.dtypes

id_hotel      int64
nome_hotel      str
cidade          str
estado          str
categoria       str
n_quartos     int64
dtype: object

In [64]:
#criando dicionário de correção para palavras com grafias 
df_quartos['tipo_quarto'] = df_quartos['tipo_quarto'].str.replace({'Standart': 'Standard','STANDARD': 'Standard','standard': 'Standard','STANDART': 'Standard'})
df_quartos['tipo_quarto'] = df_quartos['tipo_quarto'].str.replace({'superior': 'Superior','SUPERIOR': 'Superior'})
df_quartos['tipo_quarto'].value_counts()

tipo_quarto
Standard        19
Superior        14
Luxo            11
Suite            9
Suite master     5
Name: count, dtype: int64

In [17]:
#substituindo quartos com capacidade -1 e 0 para a capacidade do tipo de quartos equivalente (suite)
#substituindo quartos com capacidade -2 para a capacidade do tipo de quartos equivalente (luxo)
df_quartos['capacidade'] = df_quartos['capacidade'].replace({0:5,-1:5})
df_quartos['capacidade'] = df_quartos['capacidade'].replace(-2,4)

In [18]:
#transformando valor_base do quarto Q004 de NaN para o mesmo valor do mesmo tipo de quarto no mesmo hotel
df_quartos.loc[(df_quartos['id_hotel'] == 1) & (df_quartos['id_quarto'] == 'Q004'), 'valor_base'] = 320.00

In [19]:
#transformando valor_base do quarto Q018 de NaN para o mesmo valor do mesmo tipo de quarto no mesmo hotel
df_quartos.loc[(df_quartos['id_hotel'] == 2) & (df_quartos['id_quarto'] == 'Q018'), 'valor_base'] = 420.00

In [20]:
#transformando valor_base do quarto Q038 de NaN para o mesmo valor do mesmo tipo de quarto no mesmo hotel
df_quartos.loc[(df_quartos['id_hotel'] == 4) & (df_quartos['id_quarto'] == 'Q038'), 'valor_base'] = 350.00

In [21]:
#transformando valor_base do quarto Q051 de NaN para o mesmo valor do mesmo tipo de quarto no mesmo hotel
df_quartos.loc[(df_quartos['id_hotel'] == 5) & (df_quartos['id_quarto'] == 'Q051'), 'valor_base'] = 620.00

In [65]:
#removendo a linha 57 do dataframe onde estava o id_quarto Q058, que é inexistente
df_quartos.drop(index=57)

,id_quarto,id_hotel,tipo_quarto,capacidade,valor_base,andar,vista
0,Q001,1,Standard,2,320.0,1,Jardim
1,Q002,1,Standard,2,320.0,2,Jardim
2,Q003,1,Standard,2,320.0,3,Jardim
3,Q004,1,Standard,2,320.0,4,Jardim
4,Q005,1,Superior,3,480.0,5,Mar
5,Q006,1,Superior,3,480.0,6,Mar
6,Q007,1,Superior,3,480.0,7,Mar
7,Q008,1,Luxo,4,750.0,8,Mar
8,Q009,1,Luxo,4,750.0,9,Mar
9,Q010,1,Suite,5,1200.0,10,Panorâmica
10,Q011,1,Suite,5,1200.0,11,Panorâmica
11,Q012,1,Suite master,6,2200.0,12,Panorâmica
12,Q013,2,Standard,2,280.0,1,Jardim
13,Q014,2,Standard,2,280.0,2,Jardim
14,Q015,2,Standard,2,280.0,3,Jardim
15,Q016,2,Superior,3,420.0,4,Piscina
16,Q017,2,Superior,3,420.0,5,Piscina
17,Q018,2,Superior,3,420.0,6,Piscina
18,Q019,2,Luxo,4,680.0,7,Mar
19,Q020,2,Luxo,4,680.0,8,Mar
20,Q021,2,Suite,5,1100.0,9,Panorâmica
21,Q022,2,Suite,5,1100.0,10,Panorâmica
22,Q023,2,Suite master,6,1950.0,11,Panorâmica
23,Q024,3,Standard,2,260.0,1,Jardim
24,Q025,3,Standard,2,260.0,2,Jardim
25,Q026,3,Standard,2,260.0,3,Jardim
26,Q027,3,Superior,3,400.0,4,Piscina
27,Q028,3,Superior,3,400.0,5,Piscina
28,Q029,3,Superior,3,400.0,6,Piscina
29,Q030,3,Luxo,4,640.0,7,Mar
30,Q031,3,Luxo,4,640.0,8,Mar
31,Q032,3,Suite,5,1050.0,9,Panorâmica
32,Q033,3,Suite,5,1050.0,10,Panorâmica
33,Q034,3,Suite master,6,1900.0,11,Panorâmica
34,Q035,4,Standard,2,350.0,1,Cidade
35,Q036,4,Standard,2,350.0,2,Cidade
36,Q037,4,Standard,2,350.0,3,Cidade
37,Q038,4,Standard,2,350.0,4,Cidade
38,Q039,4,Superior,3,520.0,5,Cidade
39,Q040,4,Superior,3,520.0,6,Cidade
40,Q041,4,Luxo,4,820.0,7,Mar
41,Q042,4,Luxo,4,820.0,8,Mar
42,Q043,4,Suite,5,1350.0,9,Panorâmica
43,Q044,4,Suite master,6,2500.0,10,Panorâmica
44,Q045,5,Standard,2,420.0,1,Cidade
45,Q046,5,Standard,2,420.0,2,Cidade
46,Q047,5,Standard,2,420.0,3,Cidade
47,Q048,5,Standard,2,420.0,4,Cidade
48,Q049,5,Superior,3,620.0,5,Cidade
49,Q050,5,Superior,3,620.0,6,Cidade
50,Q051,5,Superior,3,620.0,7,Cidade
51,Q052,5,Luxo,4,950.0,8,Cidade
52,Q053,5,Luxo,4,950.0,9,Cidade
53,Q054,5,Luxo,4,950.0,10,Cidade
54,Q055,5,Suite,5,1600.0,11,Panorâmica
55,Q056,5,Suite,5,1600.0,12,Panorâmica
56,Q057,5,Suite master,6,2800.0,15,Panorâmica

In [23]:
#formatando a coluna nome da base hóspedes para garantir que os nomes estejam padronizados sem espaço extra e com a primeira letra maiúscula
df_hospedes['nome'] = df_hospedes['nome'].str.strip().str.title()
df_hospedes.head(2)

,id_hospede,nome,email,telefone,cidade_origem,estado,data_nascimento,genero
0,1,Carlos Pereira,carlos.pereira76@outlook.com,(24) 99935-2424,Rio de Janeiro,RJ,1969-03-24,M
1,2,Diego Alves,diego.alves29@outlook.com,(36) 99928-7873,Manaus,AM,1993-01-18,M

In [24]:
df_hospedes.head(2)

,id_hospede,nome,email,telefone,cidade_origem,estado,data_nascimento,genero
0,1,Carlos Pereira,carlos.pereira76@outlook.com,(24) 99935-2424,Rio de Janeiro,RJ,1969-03-24,M
1,2,Diego Alves,diego.alves29@outlook.com,(36) 99928-7873,Manaus,AM,1993-01-18,M

In [25]:
#corrigindo siglas de UF erradas
ufs_corretas = {'rio de janeiro': 'RJ', 'Sp':'SP', 'RRJ':'RJ','NaN':'RS' }
df_hospedes['estado'] = df_hospedes['estado'].replace(ufs_corretas)
df_hospedes['estado'].value_counts()

estado
MG    44
DF    43
AM    42
SP    42
RS    41
PR    40
RJ    38
CE    37
PE    37
BA    37
Name: count, dtype: int64

In [66]:
#corrigindo forma de data e atribuindo NaN a formatos inválidos
df_hospedes['data_nascimento'] = pd.to_datetime(df_hospedes['data_nascimento'], errors='coerce')
df_hospedes

,id_hospede,nome,email,telefone,cidade_origem,estado,data_nascimento,genero
0,1,Carlos Pereira,carlos.pereira76@outlook.com,(24) 99935-2424,Rio de Janeiro,RJ,1969-03-24,M
1,2,Diego Alves,diego.alves29@outlook.com,(36) 99928-7873,Manaus,AM,1993-01-18,M
2,3,Bruno Ribeiro,bruno.ribeiro49@gmail.com,(54) 92674-2519,Belo Horizonte,MG,1972-03-07,M
3,4,Sandra Pereira,sandra.pereira71@yahoo.com,(26) 97201-2291,Fortaleza,CE,2001-08-18,F
4,5,Cristina Ferreira,carlossilva.semdominio,(48) 92307-4814,Recife,PE,1957-11-08,F
...,...,...,...,...,...,...,...,...
395,396,Carolina Castro,carolina.castro87@hotmail.com,(19) 97269-4610,Fortaleza,CE,1985-02-09,F
396,397,Renata Moreira,renata.moreira12@outlook.com,(44) 95067-5706,Manaus,AM,1955-12-27,F
397,398,Fernanda Dias,fernanda.dias96@hotmail.com,(38) 95408-3994,Salvador,BA,1985-06-12,F
398,399,Felipe Alves,felipe.alves14@gmail.com,(42) 96833-3555,São Paulo,SP,1968-04-07,M
399,400,Sandra Silva,sandra.silva74@yahoo.com,(90) 96167-9066,Manaus,AM,1957-08-12,F

In [ ]:
#df_hospedess_data_inconsistentes = df_hospedes.loc[(df_hospedes['data_nascimento'] > 2003)  & (df_hospedes['data_nascimento'] < 1955)

In [27]:
#corrigindo siglas de gênero fora do padrão
genero_padronizado = {'Masculino': 'M', 'fem':'F', 'NaN':'F'}
df_hospedes['genero'] = df_hospedes['genero'].replace(genero_padronizado)
df_hospedes['genero'].value_counts()

genero
F    201
M    200
Name: count, dtype: int64

In [28]:
#encontrando datas inválidas com checkout antes do checkin
datas_invalidas = df_reservas_total[df_reservas_total['data_checkout'] < df_reservas_total['data_checkin']]
datas_invalidas

,id_reserva,id_hospede,id_quarto,id_hotel,data_checkin,data_checkout,canal_reserva,valor_diaria,status_reserva,data_reserva
10,11,61,Q046,5,2024-06-08,2024-06-06,Booking.com,2180.71,Confirmada,2024-05-29
45,46,398,Q008,1,2023-07-07,2023-07-05,Site Próprio,2228.90,Confirmada,2023-06-27
112,113,17,Q003,1,2024-03-11,2024-03-09,Agência de Viagem,2719.12,Confirmada,2024-02-08
278,279,112,Q002,1,2023-05-05,2023-05-03,Agência de Viagem,295.33,Confirmada,2023-03-19
401,402,356,Q036,4,2023-07-01,2023-06-29,Booking.com,1068.64,Confirmada,2023-05-19
1050,1051,52,Q014,2,2025-08-03,2025-08-02,Telefone,1409.41,Confirmada,2025-07-01
1222,1223,252,Q047,5,2025-03-06,2025-03-05,Booking.com,737.87,Confirmada,2025-01-27
1410,1411,16,Q032,3,2025-03-10,2025-03-09,Telefone,1799.67,Confirmada,2025-02-18

In [29]:
#marcando datas inválidas com NaN
#df_reservas_total.loc[df_reservas_total['data_checkout'] < df_reservas_total['data_checkin'], 'data_checkout'] = np.nan

In [30]:
df_reservas_total.sort_values(by='valor_diaria', ascending=False).head(10)

,id_reserva,id_hospede,id_quarto,id_hotel,data_checkin,data_checkout,canal_reserva,valor_diaria,status_reserva,data_reserva
511,512,57,Q025,3,2023-05-04,2023-05-12,Booking.com,24637.28,Confirmada,2023-05-03
33,34,144,Q001,1,2024-04-28,2024-05-03,Booking.com,23785.17,Confirmada,2024-04-05
177,178,130,Q057,5,2023-06-12,2023-06-18,Telefone,19486.09,Confirmada,2023-04-20
320,321,213,Q039,4,2023-06-16,2023-06-17,Expedia,19122.22,Confirmada,2023-05-06
688,689,354,Q043,4,2024-10-08,2024-10-10,NaN,16283.31,Confirmada,2024-08-20
1467,1468,367,Q037,4,2025-02-16,2025-02-23,Site Próprio,2894.93,Confirmada,2025-01-31
1260,1261,83,Q031,3,2025-05-31,2025-06-06,Site Próprio,2894.43,Confirmada,2025-04-27
1413,1414,271,Q023,2,2025-01-31,2025-02-02,Expedia,2887.11,Confirmada,2025-01-25
1115,1116,350,Q033,3,2025-04-09,2025-04-14,Telefone,2879.12,Confirmada,2025-02-24
1100,1101,340,Q038,4,2025-01-14,2025-01-19,Expedia,2873.13,Cancelada,2024-12-23

In [31]:
#removendo linhas com valores negativos
#df_reservas_negativas = df_reservas_total[df_reservas_total['valor_diaria'] >= 0]
#df_quartos.drop(index=150)

In [32]:
#substituindo valores zerados por NaN
#df_reservas_total['valor_diaria'] = df_reservas_total['valor_diaria'].replace('0','NaN')

In [33]:
#removendo as linhas com NaN
#remov_nan = df_reservas_total.drop(df_reservas_total[df_reservas_total['valor_diaria'].isna()])

In [68]:
#Valores de diária extremamente altos,acima de R$ 15.000 (outliers)
df_reservas_quarto = df_reservas_total.groupby ([ 'id_reserva', 'data_checkin','id_quarto'] )['valor_diaria'].sum().reset_index()
df_reservas_quarto.sort_values(by='valor_diaria', ascending=False).head(5)

     id_reserva data_checkin id_quarto  valor_diaria
511         512   2023-05-04      Q025      24637.28
33           34   2024-04-28      Q001      23785.17
177         178   2023-06-12      Q057      19486.09
320         321   2023-06-16      Q039      19122.22
688         689   2024-10-08      Q043      16283.31

In [35]:
array_df_reservas = np.array(df_reservas_quarto['valor_diaria'])
q1_df_reservas = np.percentile(array_df_reservas, 25)
q2_df_reservas = np.percentile(array_df_reservas, 50)
q3_df_reservas = np.percentile(array_df_reservas, 75)
media = np.mean(array_df_reservas)
mediana = np.median(array_df_reservas)
distancia = (media - mediana) / mediana

print(f'1º quartil: {q1_df_reservas}')
print(f'2º quartil (mediana): {q2_df_reservas}')
print(f'3º quartil: {q3_df_reservas}')
print(f'média: {media}')
print(f'mediana: {mediana}')
print(f'distância: {round(distancia * 100, 2)}%')
print('\nConclusão')  
print('Podemos usar a média como medida de tendência central uma vez que a distância entre média e mediana é de 5.49%.')
print(f'valor médio das estadias R$ {media:.2f}')
#criando limites superior e inferior
iqr = q3_df_reservas - q1_df_reservas
limite_superior = q3_df_reservas + (iqr * 1.5)
limite_inferior = q3_df_reservas - (iqr * 1.5)
print(f'limite superior: {limite_superior}')
print(f'limite inferior: {limite_inferior:.2f}')

1º quartil: 903.31
2º quartil (mediana): 1549.015
3º quartil: 2185.3475
média: 1605.2808799999998
mediana: 1549.015
distância: 3.63%

Conclusão
Podemos usar a média como medida de tendência central uma vez que a distância entre média e mediana é de 5.49%.
valor médio das estadias R$ 1605.28
limite superior: 4108.4037499999995
limite inferior: 262.29

In [36]:
outliers_sup_df_reservas_quarto = df_reservas_quarto.loc[(df_reservas_quarto['valor_diaria'] >= limite_superior)]
outliers_sup_df_reservas_quarto = outliers_sup_df_reservas_quarto.sort_values(by='valor_diaria')
outliers_sup_df_reservas_quarto.head(5)

     id_reserva  valor_diaria
688         689      16283.31
320         321      19122.22
177         178      19486.09
33           34      23785.17
511         512      24637.28

In [37]:
outliers_inf_df_reservas_quarto = df_reservas_quarto.loc[(df_reservas_quarto['valor_diaria'] <= limite_inferior)]
outliers_inf_df_reservas_quarto = outliers_inf_df_reservas_quarto.sort_values(by='valor_diaria')
outliers_inf_df_reservas_quarto.head(2)

     id_reserva  valor_diaria
89           90       -274.84
234         235       -212.66

In [38]:
#tratando valores de diária extremamente altos,acima de R$ 15.000 (outliers). 
#ajustei cada reserva multiplicando o valor base do quarto pelo número de diárias. formato{id_reserva:(valor_base * número de diarias)}

valores_ajustados_por_id_reserva = {
                                    512:2080,
                                    34:1600,
                                    178:16800,
                                    321:520,
                                    689:2700
}

In [39]:
#padronizando grafias na coluna status_reserva
status_reserva_padronizada = {
                            'Cancelado': 'Cancelada',
                            'no-show': 'No-show',
                            'CONFIRMADA': 'Confirmada',
                            'confirmada': 'Confirmada'
}
df_reservas_total['status_reserva'] = df_reservas_total['status_reserva'].replace(status_reserva_padronizada)
df_reservas_total['status_reserva'].value_counts()

status_reserva
Confirmada     1314
Cancelada        90
No-show          51
Overbooking      45
Name: count, dtype: int64

In [40]:
#padronizando grafias na coluna canal_reserva
canal_reserva_padronizada = {
                            'EXPEDIA': 'Expedia',
                            'site próprio': 'Site Próprio',
                            'Agencia de Viagem':'Agência de Viagem',
                            'booking.com':'Booking.com'
}
df_reservas_total['canal_reserva'] = df_reservas_total['canal_reserva'].replace(canal_reserva_padronizada)
df_reservas_total['canal_reserva'].value_counts()

canal_reserva
Expedia              319
Site Próprio         316
Booking.com          306
Agência de Viagem    279
Telefone             275
Name: count, dtype: int64

In [41]:
#identificando id_hospedes sem correspondentes na base de hospedes
id_hospede_acima_400 = df_reservas_total.loc[(df_reservas_total['id_hospede'] > 400)]
id_hospede_acima_400.sort_values(by='id_hospede', ascending=False)

,id_reserva,id_hospede,id_quarto,id_hotel,data_checkin,data_checkout,canal_reserva,valor_diaria,status_reserva,data_reserva
499,500,975,Q040,4,2023-08-22,2023-09-01,Agência de Viagem,1295.31,Confirmada,2023-06-24
1190,1191,938,Q001,1,2025-04-05,2025-04-06,Agência de Viagem,1274.29,Cancelada,2025-02-23
188,189,853,Q050,5,2023-04-19,2023-04-28,Expedia,1611.99,Confirmada,2023-03-23
305,306,815,Q023,2,2024-11-16,2024-11-25,Agência de Viagem,715.81,Confirmada,2024-09-22
1070,1071,678,Q033,3,2025-03-08,2025-03-15,Booking.com,1418.66,Confirmada,2025-02-20
77,78,632,Q005,1,2024-10-06,2024-10-10,Site Próprio,1743.24,Confirmada,2024-09-02
720,721,599,Q037,4,2023-11-08,2023-11-20,Expedia,1737.42,Confirmada,2023-11-03
1320,1321,531,Q048,5,2025-05-22,2025-05-31,Expedia,1463.60,Cancelada,2025-05-16

In [42]:
#excluindo id_hospedes sem correspondentes na base de hospedes
#df_reservas_total = df_reservas_total.drop(id_hospede_acima_400.index)

In [43]:
#identificando reservas inválidas com data da reserva depois da data de checkin
datas_invalidas_reservas = df_reservas_total[df_reservas_total['data_reserva'] > df_reservas_total['data_checkin']]
datas_invalidas_reservas

,id_reserva,id_hospede,id_quarto,id_hotel,data_checkin,data_checkout,canal_reserva,valor_diaria,status_reserva,data_reserva
50,51,261,Q031,3,2024-06-30,2024-07-13,Agência de Viagem,1544.77,Confirmada,2024-07-04
120,121,29,Q039,4,2023-01-23,2023-01-27,Agência de Viagem,2506.36,Confirmada,2023-01-27
333,334,14,Q043,4,2024-06-27,2024-07-10,Telefone,592.65,Confirmada,2024-06-29
610,611,347,Q043,4,2023-03-03,2023-03-14,Agência de Viagem,1508.02,Confirmada,2023-03-04

In [44]:
#excluindo reservas inválidas com data da reserva depois da data de checkin
#df_reservas_total = df_reservas_total.drop(datas_invalidas_reservas.index)

In [45]:
#na base avaliacoes.csv, na coluna nota_geral, atribuindo nota 7 à string 'bom'
df_avaliacoes_total['nota_geral'] = df_avaliacoes_total['nota_geral'].str.replace('bom', '7')
df_avaliacoes_total['nota_geral'] = df_avaliacoes_total['nota_geral'].str.replace(',','.')

In [46]:
#transformando o tipo de dado de string para float
df_avaliacoes_total['nota_geral'] = df_avaliacoes_total['nota_geral'].astype(float)

In [47]:
#transformando o tipo de dado de string para float
#atribuindo nota 9 à string 'ótimo'

df_avaliacoes_total['nota_atendimento'] = df_avaliacoes_total['nota_atendimento'].str.replace('ótimo','9')
df_avaliacoes_total['nota_atendimento'] = df_avaliacoes_total['nota_atendimento'].str.replace(',','.').astype(float)

In [48]:
#transformando o tipo de dado de string para float
#atribuindo nota 8 à string 'muito bom'
df_avaliacoes_total['nota_custo_beneficio'] = df_avaliacoes_total['nota_custo_beneficio'].str.replace('muito bom','8')
df_avaliacoes_total['nota_custo_beneficio'] = df_avaliacoes_total['nota_custo_beneficio'].str.replace(',','.').astype(float)

In [49]:
#transformando de string para datetime
df_avaliacoes_total['data_avaliacao'] = pd.to_datetime(df_avaliacoes_total['data_avaliacao'])
df_avaliacoes_total.dtypes

id_avaliacao                     int64
id_reserva                       int64
nota_geral                     float64
nota_limpeza                   float64
nota_atendimento               float64
nota_custo_beneficio           float64
comentario                         str
data_avaliacao          datetime64[us]
dtype: object

In [ ]:
#removendo avaliações fora do range(acima de 10 ou negativos)
df_avaliacoes_total['nota_geral']

nota_geral
 9.4     20
 8.3     20
 8.9     18
 7.1     18
 6.5     17
 6.7     17
 6.0     16
 9.8     16
 9.2     16
 8.1     15
 8.6     15
 8.5     15
 7.2     15
 8.4     15
 6.8     15
 6.3     15
 5.5     15
 6.4     15
 9.3     15
 6.2     15
 5.3     15
 7.7     15
 5.7     15
 7.8     14
 5.1     14
 8.7     14
 6.1     14
 7.0     14
 9.0     14
 5.6     14
 7.5     14
 5.4     13
 7.9     13
 9.5     13
 5.9     13
 9.1     13
 9.7     13
 6.6     12
 7.4     12
 7.3     12
 8.2     12
 7.6     10
 9.6     10
 8.0     10
 10.0     9
 5.8      8
 8.8      8
 5.2      7
 5.0      5
 9.9      4
 6.9      3
-3.0      2
 0.0      2
 11.0     1
Name: count, dtype: int64

In [51]:
datasets = {
    'Reservas': df_reservas_total,
    'Hóspedes': df_hospedes,
    'Quartos': df_quartos,
    'Hotéis': df_hoteis,
    'Avaliações': df_avaliacoes
}

In [52]:
df_hospedes.drop_duplicates(inplace=True)
#para remover duplicadas de hospedes

In [53]:
for nome, df in datasets.items():
    print(f"--- Diagnóstico da Tabela: {nome} ---")
    print(f"Linhas: {df.shape[0]} | Colunas: {df.shape[1]}")
    print(f"Valores Nulos:\n{df.isnull().sum()[df.isnull().sum() > 0]}") # Mostra apenas colunas com nulos
    print(f"Linhas Duplicadas: {df.duplicated().sum()}")
    print("-" * 40 + "\n")

--- Diagnóstico da Tabela: Reservas ---
Linhas: 1500 | Colunas: 10
Valores Nulos:
canal_reserva    5
valor_diaria     6
dtype: int64
Linhas Duplicadas: 0
----------------------------------------

--- Diagnóstico da Tabela: Hóspedes ---
Linhas: 400 | Colunas: 8
Valores Nulos:
cidade_origem      1
estado             1
data_nascimento    1
genero             1
dtype: int64
Linhas Duplicadas: 0
----------------------------------------

--- Diagnóstico da Tabela: Quartos ---
Linhas: 58 | Colunas: 7
Valores Nulos:
Series([], dtype: int64)
Linhas Duplicadas: 0
----------------------------------------

--- Diagnóstico da Tabela: Hotéis ---
Linhas: 5 | Colunas: 6
Valores Nulos:
Series([], dtype: int64)
Linhas Duplicadas: 0
----------------------------------------

--- Diagnóstico da Tabela: Avaliações ---
Linhas: 685 | Colunas: 8
Valores Nulos:
nota_limpeza         4
nota_atendimento     2
comentario          53
dtype: int64
Linhas Duplicadas: 0
----------------------------------------

In [54]:
#corrigindo notas que vieram como texto ou com vírgula
for col in ['nota_geral', 'nota_custo_beneficio']:
    df_avaliacoes[col] = df_avaliacoes[col].astype(str).str.replace(',', '.')
    df_avaliacoes[col] = pd.to_numeric(df_avaliacoes[col], errors='coerce')

In [55]:
#tratando notas(negativas ou acima de 10)
df_avaliacoes['nota_geral'] = df_avaliacoes['nota_geral'].apply(lambda x: np.nan if x < 0 or x > 10 else x)

In [56]:
#convertendo datas
df_reservas_total['data_checkin'] = pd.to_datetime(df_reservas_total['data_checkin'])
df_reservas_total['data_checkout'] = pd.to_datetime(df_reservas_total['data_checkout'])
df_reservas_total['data_reserva'] = pd.to_datetime(df_reservas_total['data_reserva'])

In [57]:
#preenchendo canais de reserva nulos e diárias zeradas
df_reservas_total['canal_reserva'].fillna('Desconhecido', inplace=True)
df_reservas_total['valor_diaria'].fillna(df_reservas_total['valor_diaria'].median(), inplace=True)

C:\Users\bruno.uchoa\AppData\Local\Temp\ipykernel_19788\1244934350.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df_reservas_total['canal_reserva'].fillna('Desconhecido', inplace=True)
C:\Users\bruno.uchoa\AppData\Local\Temp\ipykernel_19788\1244934350.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df_reservas_total['valor_diaria'].fillna(df_reservas_total['valor_diaria'].median(), inplace=True)

0       2344.25
1        469.17
2       2358.47
3       1743.13
4        617.85
         ...
1495     600.66
1496     835.44
1497    2235.72
1498    2495.88
1499     625.82
Name: valor_diaria, Length: 1500, dtype: float64

In [58]:
#padronizando tipos de quarto (tirando erros de digitação como 'Standart')
df_quartos['tipo_quarto'] = df_quartos['tipo_quarto'].str.capitalize().str.replace('Standart', 'Standard')
df_quartos['valor_base'].fillna(df_quartos['valor_base'].median(), inplace=True)

C:\Users\bruno.uchoa\AppData\Local\Temp\ipykernel_19788\284962005.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df_quartos['valor_base'].fillna(df_quartos['valor_base'].median(), inplace=True)

0      320.0
1      320.0
2      320.0
3      320.0
4      480.0
5      480.0
6      480.0
7      750.0
8      750.0
9     1200.0
10    1200.0
11    2200.0
12     280.0
13     280.0
14     280.0
15     420.0
16     420.0
17     420.0
18     680.0
19     680.0
20    1100.0
21    1100.0
22    1950.0
23     260.0
24     260.0
25     260.0
26     400.0
27     400.0
28     400.0
29     640.0
30     640.0
31    1050.0
32    1050.0
33    1900.0
34     350.0
35     350.0
36     350.0
37     350.0
38     520.0
39     520.0
40     820.0
41     820.0
42    1350.0
43    2500.0
44     420.0
45     420.0
46     420.0
47     420.0
48     620.0
49     620.0
50     620.0
51     950.0
52     950.0
53     950.0
54    1600.0
55    1600.0
56    2800.0
57     300.0
Name: valor_base, dtype: float64

In [71]:
from IPython.display import display, Markdown

#histórico de reservas (2023-2024)
display(Markdown("### 1. Histórico de Reservas (Período 2023-2024)"))
display(Markdown("*Arquivo: `reservas.csv`*"))
display(df_reservas_total.head(21))

#cadastro dos hóspedes
display(Markdown("---"))
display(Markdown("### 2. Cadastro de Hóspedes (Dados pessoais, origem e contato)"))
display(Markdown("*Arquivo: `hospedes.csv`*"))
display(df_hospedes.head(21))

#notas e comentários das avaliações
display(Markdown("---"))
display(Markdown("### 3. Avaliações (Notas e comentários pós-estadia)"))
display(Markdown("*Arquivo: `avaliacoes.csv`*"))
display(df_avaliacoes.head(21))

#catálogo de quartos
display(Markdown("---"))
display(Markdown("### 4. Catálogo de Quartos (Tipo, capacidade e valor base)"))
display(Markdown("*Arquivo: `quartos.csv`*"))
display(df_quartos.head(21))

#dados cadastrais das unidades (hotéis)
display(Markdown("---"))
display(Markdown("### 5. Dados Cadastrais das Unidades (Cidade, estado e categoria)"))
display(Markdown("*Arquivo: `hoteis.csv`*"))
display(df_hoteis.head(5))

### 1. Histórico de Reservas (Período 2023-2024)

*Arquivo: `reservas.csv`*

,id_reserva,id_hospede,id_quarto,id_hotel,data_checkin,data_checkout,canal_reserva,valor_diaria,status_reserva,data_reserva
0,1,203,Q026,3,2024-10-28,2024-10-29,Site Próprio,2344.25,Confirmada,2024-10-21
1,2,30,Q033,3,2024-06-03,2024-06-07,Site Próprio,469.17,Confirmada,2024-05-07
2,3,47,Q004,1,2024-07-18,2024-07-25,Site Próprio,2358.47,Confirmada,2024-07-10
3,4,322,Q023,2,2024-08-19,2024-08-20,Telefone,1743.13,Confirmada,2024-08-15
4,5,286,Q013,2,2023-05-17,2023-05-22,Agência de Viagem,617.85,Confirmada,2023-05-09
5,6,287,Q049,5,2024-11-29,2024-12-02,Site Próprio,1733.08,No-show,2024-10-19
6,7,50,Q018,2,2024-07-14,2024-07-26,Site Próprio,1689.14,Confirmada,2024-06-04
7,8,349,Q020,2,2024-06-28,2024-07-05,Expedia,1437.28,Confirmada,2024-04-29
8,9,154,Q040,4,2023-09-12,2023-09-25,Booking.com,2032.44,Confirmada,2023-08-27
9,10,154,Q010,1,2024-06-21,2024-06-29,Expedia,2110.09,Confirmada,2024-06-02
10,11,61,Q046,5,2024-06-08,2024-06-06,Booking.com,2180.71,Confirmada,2024-05-29
11,12,21,Q041,4,2024-11-15,2024-11-17,Telefone,1711.22,Confirmada,2024-09-19
12,13,356,Q029,3,2023-12-25,2024-01-04,Agência de Viagem,1728.73,Confirmada,2023-11-25
13,14,139,Q002,1,2024-04-30,2024-05-12,Site Próprio,404.71,Confirmada,2024-03-16
14,15,296,Q034,3,2024-11-28,2024-12-12,Agência de Viagem,975.72,Confirmada,2024-11-03
15,16,237,Q024,3,2023-12-30,2024-01-02,Telefone,548.59,Overbooking,2023-12-26
16,17,67,Q017,2,2023-09-11,2023-09-18,Agência de Viagem,2587.88,Overbooking,2023-08-10
17,18,230,Q003,1,2024-02-16,2024-02-25,Expedia,2502.63,Overbooking,2023-12-25
18,19,143,Q043,4,2024-12-24,2024-12-31,Expedia,1990.94,No-show,2024-11-29
19,20,43,Q015,2,2023-06-30,2023-07-03,Booking.com,1929.22,Confirmada,2023-06-29
20,21,94,Q044,4,2023-09-27,2023-10-02,Site Próprio,621.47,Confirmada,2023-08-23

---

### 2. Cadastro de Hóspedes (Dados pessoais, origem e contato)

*Arquivo: `hospedes.csv`*

,id_hospede,nome,email,telefone,cidade_origem,estado,data_nascimento,genero
0,1,Carlos Pereira,carlos.pereira76@outlook.com,(24) 99935-2424,Rio de Janeiro,RJ,1969-03-24,M
1,2,Diego Alves,diego.alves29@outlook.com,(36) 99928-7873,Manaus,AM,1993-01-18,M
2,3,Bruno Ribeiro,bruno.ribeiro49@gmail.com,(54) 92674-2519,Belo Horizonte,MG,1972-03-07,M
3,4,Sandra Pereira,sandra.pereira71@yahoo.com,(26) 97201-2291,Fortaleza,CE,2001-08-18,F
4,5,Cristina Ferreira,carlossilva.semdominio,(48) 92307-4814,Recife,PE,1957-11-08,F
5,6,Mariana Carvalho,mariana.carvalho69@hotmail.com,(98) 92169-3803,Belo Horizonte,MG,1968-11-09,F
6,7,Amanda Dias,amanda.dias41@outlook.com,(18) 94752-1525,Rio de Janeiro,RJ,1998-06-27,M
7,8,Paulo Martins,paulo.martins34@hotmail.com,11987654321,Rio de Janeiro,RJ,1996-08-13,M
8,9,Cristina Ribeiro,cristina.ribeiro12@gmail.com,(28) 99348-9085,Brasília,DF,1980-06-08,F
9,10,Bruno Ribeiro,bruno.ribeiro33@gmail.com,(87) 98668-9669,Brasília,DF,1959-07-13,M
10,11,Ricardo Pereira,ricardo.pereira93@yahoo.com,(31) 98433-1053,NaN,MG,1962-05-14,M
11,12,Daniel Souza,emailsemarrobasemnada,(36) 93504-7126,São Paulo,SP,1995-09-20,M
12,13,Henrique Martins,henrique.martins31@gmail.com,(50) 94923-1949,Porto Alegre,RS,1956-02-12,M
13,14,Fernanda Dias,fernanda.dias68@outlook.com,(81) 93705-5342,Salvador,BA,1963-11-16,F
14,15,Marcos Gomes,marcos.gomes9@yahoo.com,(26) 95061-4681,Belo Horizonte,RJ,1983-09-15,M
15,16,Paulo Alves,paulo.alves5@yahoo.com,(18) 94750-2104,Fortaleza,CE,1959-12-21,M
16,17,André Nascimento,andré.nascimento61@outlook.com,+55 (21) 98765-4321,Rio de Janeiro,RJ,1989-03-24,M
17,18,Gustavo Carvalho,gustavo.carvalho52@yahoo.com,(17) 92612-1993,Curitiba,PR,1981-08-28,M
18,19,Felipe Ferreira,felipe.ferreira60@hotmail.com,(65) 94006-5563,Rio de Janeiro,RJ,1989-08-05,F
19,20,Leonardo Dias,leonardo.dias22@outlook.com,(12) 92528-4872,Recife,PE,1899-03-15,M
20,21,Eduardo Santos,eduardo.santos55@outlook.com,(44) 98454-5673,Salvador,BA,1979-01-13,M

---

### 3. Avaliações (Notas e comentários pós-estadia)

*Arquivo: `avaliacoes.csv`*

,id_avaliacao,id_reserva,nota_geral,nota_limpeza,nota_atendimento,nota_custo_beneficio,comentario,data_avaliacao
0,1,280,NaN,7.2,8.6,8.1,Staff muito atencioso.,2023-07-13
1,2,312,9.4,5.7,9.8,5.4,Custo-benefício muito bom.,2024-05-21
2,3,727,8.1,5.4,7.7,8.4,"Ótima estadia, recomendo!",2024-05-20
3,4,964,8.6,7.4,5.9,8.6,"Ótima estadia, recomendo!",2023-04-17
4,5,726,8.5,7.8,6.0,7.4,Staff muito atencioso.,2023-06-26
5,6,850,5.2,15.0,9.0,7.6,"Atendimento muito bom, quarto confortável.",2024-06-19
6,7,899,5.8,9.1,9.9,5.9,"Hotel excelente, voltarei com certeza.",2024-09-03
7,8,944,5.8,7.4,6.0,10.0,"Ótima estadia, recomendo!",2024-08-27
8,9,204,8.6,5.3,8.9,5.3,NaN,2024-05-22
9,10,693,6.9,8.5,6.0,9.6,"Ótima estadia, recomendo!",2023-03-25
10,11,250,8.1,8.6,-1.0,8.4,Quarto limpo e bem equipado.,2023-03-09
11,12,708,7.2,8.0,8.8,9.4,"Boa localização, café da manhã delicioso.",2023-05-04
12,13,160,7.6,8.9,8.6,7.9,"Hotel excelente, voltarei com certeza.",2024-04-02
13,14,922,8.6,7.6,5.8,8.1,"Boa localização, café da manhã delicioso.",2023-11-08
14,15,244,6.5,7.3,8.8,5.5,Custo-benefício muito bom.,2023-06-08
15,16,682,0.0,8.4,9.1,6.3,Custo-benefício muito bom.,2023-11-13
16,17,779,7.8,8.0,9.6,8.5,"Ótima estadia, recomendo!",2023-11-24
17,18,205,8.9,7.9,7.1,6.2,Custo-benefício muito bom.,2023-09-18
18,19,143,8.5,6.4,5.7,9.4,Custo-benefício muito bom.,2023-04-21
19,20,81,5.4,9.5,5.5,6.8,NaN,2025-01-01
20,21,564,8.5,9.5,5.9,7.8,NaN,2023-08-24

---

### 4. Catálogo de Quartos (Tipo, capacidade e valor base)

*Arquivo: `quartos.csv`*

,id_quarto,id_hotel,tipo_quarto,capacidade,valor_base,andar,vista
0,Q001,1,Standard,2,320.0,1,Jardim
1,Q002,1,Standard,2,320.0,2,Jardim
2,Q003,1,Standard,2,320.0,3,Jardim
3,Q004,1,Standard,2,320.0,4,Jardim
4,Q005,1,Superior,3,480.0,5,Mar
5,Q006,1,Superior,3,480.0,6,Mar
6,Q007,1,Superior,3,480.0,7,Mar
7,Q008,1,Luxo,4,750.0,8,Mar
8,Q009,1,Luxo,4,750.0,9,Mar
9,Q010,1,Suite,5,1200.0,10,Panorâmica
10,Q011,1,Suite,5,1200.0,11,Panorâmica
11,Q012,1,Suite master,6,2200.0,12,Panorâmica
12,Q013,2,Standard,2,280.0,1,Jardim
13,Q014,2,Standard,2,280.0,2,Jardim
14,Q015,2,Standard,2,280.0,3,Jardim
15,Q016,2,Superior,3,420.0,4,Piscina
16,Q017,2,Superior,3,420.0,5,Piscina
17,Q018,2,Superior,3,420.0,6,Piscina
18,Q019,2,Luxo,4,680.0,7,Mar
19,Q020,2,Luxo,4,680.0,8,Mar
20,Q021,2,Suite,5,1100.0,9,Panorâmica

---

### 5. Dados Cadastrais das Unidades (Cidade, estado e categoria)

*Arquivo: `hoteis.csv`*

   id_hotel           nome_hotel          cidade estado   categoria  n_quartos
0         1       Nara Fortaleza       Fortaleza     CE  5 estrelas        120
1         2          Nara Recife          Recife     PE  4 estrelas         95
2         3        Nara Salvador        Salvador     BA  4 estrelas        100
3         4  Nara Rio de Janeiro  Rio de Janeiro     RJ  3 estrelas         80
4         5       Nara São Paulo       São Paulo     SP  5 estrelas        150

In [60]:
#configuração visual
sns.set_theme(style="white")

#distribuição das diárias
plt.figure(figsize=(10, 5))
sns.histplot(df_reservas_total['valor_diaria'], bins=30, kde=True, color='#2ecc71')

#media e mediana
media_diaria = df_reservas_total['valor_diaria'].mean()
mediana_diaria = df_reservas_total['valor_diaria'].median()
plt.axvline(media_diaria, color='#e74c3c', linestyle='--', label=f'Média: R$ {media_diaria:.2f}')
plt.axvline(mediana_diaria, color='#2980b9', linestyle='-', label=f'Mediana: R$ {mediana_diaria:.2f}')

plt.title('Distribuição do Valor das Diárias (Visão Geral)', fontsize=14, pad=15)
plt.xlabel('Valor da Diária (R$)')
plt.ylabel('Frequência')
plt.legend()
sns.despine() #remover as bordas superior e direita
plt.show()

NameError: name 'sns' is not defined

In [70]:
#cálculo dos quartis e o iqr
q1 = df_reservas_total['valor_diaria'].quantile(0.25)
q3 = df_reservas_total['valor_diaria'].quantile(0.75)
iqr = q3 - q1


limite_inferior =q1     - (  1.5 * iqr )
limite_superior = q3    +   (  1.5 * iqr )

#identificando os registros atípicos
outliers = df_reservas_total[(df_reservas_total['valor_diaria'] < limite_inferior) | 
                       (df_reservas_total['valor_diaria'] > limite_superior)]

print(f"Limite Superior detectado: R$ {limite_superior:.2f}")
print(f"Quantidade de outliers encontrados: {len(outliers)}")

display(outliers.head())

Limite Superior detectado: R$ 4099.27
Quantidade de outliers encontrados: 5

,id_reserva,id_hospede,id_quarto,id_hotel,data_checkin,data_checkout,canal_reserva,valor_diaria,status_reserva,data_reserva
33,34,144,Q001,1,2024-04-28,2024-05-03,Booking.com,23785.17,Confirmada,2024-04-05
177,178,130,Q057,5,2023-06-12,2023-06-18,Telefone,19486.09,Confirmada,2023-04-20
320,321,213,Q039,4,2023-06-16,2023-06-17,Expedia,19122.22,Confirmada,2023-05-06
511,512,57,Q025,3,2023-05-04,2023-05-12,Booking.com,24637.28,Confirmada,2023-05-03
688,689,354,Q043,4,2024-10-08,2024-10-10,NaN,16283.31,Confirmada,2024-08-20

In [ ]:
#canais de reserva
df_reservas_total['canal_reserva'] = df_reservas_total['canal_reserva'].fillna('Desconhecido').str.strip()
df_reservas_total['canal_reserva'] = df_reservas_total['canal_reserva'].replace({
    'EXPEDIA': 'Expedia',
    'site próprio': 'Site Próprio',
    'Agencia de Viagem': 'Agência de Viagem',
    'booking.com': 'Booking.com'
})

#status das reservas
df_reservas_total['status_reserva'] = df_reservas_total['status_reserva'].str.strip()
df_reservas_total['status_reserva'] = df_reservas_total['status_reserva'].replace({
    'CONFIRMADA': 'Confirmada',
    'confirmada': 'Confirmada',
    'no-show': 'No-show',
    'Cancelado': 'Cancelada'
})


#feito subplots

#configuração visual
sns.set_theme(style="white")

#criação da figura
fig, axes = plt.subplots(2, 2, figsize=(14, 10))
plt.subplots_adjust(hspace=0.4, wspace=0.3)

#evolução de reservas confirmadas
df_confirmadas = df_reservas_total[df_reservas_total['status_reserva'] == 'Confirmada'].copy()
df_confirmadas['mes_ano'] = df_confirmadas['data_checkin'].dt.to_period('M').astype(str)
evolucao = df_confirmadas.groupby('mes_ano').size()

axes[0, 0].plot(evolucao.index, evolucao.values, marker='o', color='#3498db', linewidth=2)
axes[0, 0].set_title('Evolução Mensal de Reservas Confirmadas', fontsize=12, fontweight='bold')
axes[0, 0].tick_params(axis='x', rotation=45)
axes[0, 0].grid(axis='y', linestyle='--', alpha=0.7)
sns.despine(ax=axes[0, 0])


#volume por canal de reserva
canais = df_reservas_total['canal_reserva'].value_counts()
sns.barplot(x=canais.values, y=canais.index, ax=axes[0, 1], palette='Blues_r')
axes[0, 1].set_title('Volume de Reservas por Canal', fontsize=12, fontweight='bold')
axes[0, 1].set_xlabel('Quantidade')
sns.despine(ax=axes[0, 1])


#status das reservas
status = df_reservas_total['status_reserva'].value_counts()
total_status = status.sum()

#plotando as barras verticais
sns.barplot(x=status.index, y=status.values, ax=axes[1, 0], palette='coolwarm')
axes[1, 0].set_title('Distribuição do Status das Reservas', fontsize=12, fontweight='bold')
axes[1, 0].set_ylabel('Quantidade')

#adicionando a porcentagem no topo das barras
for i, v in enumerate(status.values):
    porcentagem = (v / total_status) * 100
    axes[1, 0].text(i, v + 15, f'{porcentagem:.1f}%', ha='center', va='bottom', fontsize=10, fontweight='bold')

#aumentando o limite do eixo y
axes[1, 0].set_ylim(0, max(status.values) * 1.15)
axes[1, 0].tick_params(axis='x', rotation=15)
sns.despine(ax=axes[1, 0])


#resumo em texto
axes[1, 1].axis('off')

# Cálculos dinâmicos (refletindo os dados já limpos)
media_diaria = df_reservas_total['valor_diaria'].mean()
mediana_diaria = df_reservas_total['valor_diaria'].median()
total_reservas = len(df_reservas_total)
tx_cancelamento = (status.get('Cancelada', 0) / total_reservas) * 100
canal_top = canais.index[0]

texto_resumo = (
    "RESUMO\n\n"
    f"• Volume Total: Foram analisadas {total_reservas} reservas no período.\n\n"
    f"• Ticket: A diária média da rede está em 1615.29, "
    f"com a mediana em 1528.24.\n\n"
    f"• Aquisição: O canal que mais converte clientes é '{canal_top}'.\n\n"
    f"• Retenção: A taxa de cancelamento atual é de {tx_cancelamento:.1f}%.\n\n"
    "Conclusão Inicial: Os dados indicam a necessidade de \n"
    "investigar picos de sazonalidade e alinhar os preços \n"
    "base dos quartos com os valores efetivamente praticados."
)

# Inserindo o texto formatado no quadrante 4
axes[1, 1].text(0.05, 0.5, texto_resumo, fontsize=12, va='center', ha='left', 
                bbox=dict(facecolor='#f8f9fa', edgecolor='#dee2e6', boxstyle='round,pad=1.2'))

plt.show()

In [ ]:
#agrupando por canal e calculando a média do valor da diária
ticket_por_canal = df_reservas_total.groupby('canal_reserva')['valor_diaria'].mean().sort_values(ascending=False)

#criando a figura
plt.figure(figsize=(10, 5))
sns.barplot(x=ticket_por_canal.values, y=ticket_por_canal.index, palette='Greens_r')

#adicionando os valores
for i, v in enumerate(ticket_por_canal.values):
    plt.text(v + 50, i, f'R$ {v:.2f}', va='center', fontsize=10, fontweight='bold')

plt.title('Ticket Médio por Canal de Vendas', fontsize=14, fontweight='bold', pad=15)
plt.xlabel('Ticket Médio (R$)')
plt.xlim(0, max(ticket_por_canal.values) * 1.2) # Dá espaço para o texto
sns.despine()
plt.show()

#BREVE RELATO
#Aquele "Desconhecido" apareceu sorrateiramente por um motivo bem específico: na tabela original reservas.csv, 
# algumas linhas estavam com o canal de reserva em branco (valores nulos ou NaN). Na etapa de limpeza, 
# o código preencheu esses vazios com a palavra "Desconhecido".
#O mais curioso (e que justifica seu estranhamento) é que o ticket médio desse grupo "Desconhecido" 
# deu R$ 4.228,10, enquanto os canais normais giram em torno de R$ 1.500. 
# Isso é um forte indício de que esses registros sem canal mapeado são, na verdade, 
# aqueles outliers (valores atípicos). 
# Provavelmente são reservas manuais de suítes presidenciais ou pacotes especiais de grandes empresas 
# que não passaram pelos sistemas comuns de vendas.

In [ ]:

#filtrando para remover a linha "desconhecido"
df_canais_reais = df_reservas_total[df_reservas_total['canal_reserva'] != 'Desconhecido']

#agrupando por canal e calculando a média do valor da diária
ticket_por_canal = df_canais_reais.groupby('canal_reserva')['valor_diaria'].mean().sort_values(ascending=False)

#criando a figura
plt.figure(figsize=(10, 5))
sns.barplot(x=ticket_por_canal.values, y=ticket_por_canal.index, palette='Greens_r')

#adicionando os valores de ticket médio nas pontas das barras
for i, v in enumerate(ticket_por_canal.values):
    plt.text(v + 30, i, f'R$ {v:.2f}', va='center', fontsize=10, fontweight='bold')

plt.title('Ticket Médio por Canal de Vendas (Canais Oficiais)', fontsize=14, fontweight='bold', pad=15)
plt.xlabel('Ticket Médio (R$)')
plt.xlim(0, max(ticket_por_canal.values) * 1.2) # Garante espaço para o texto não cortar
sns.despine()
plt.show()

#exibindo o ranking em texto logo abaixo
print("Ranking de Ticket Médio por Canal:")
print(ticket_por_canal)

#BREVE RELATO
#Sem o valor discrepante de R$ 4.200 puxando a régua do gráfico para cima, 
# a escala automática do Matplotlib se ajusta perfeitamente às barras de R$ 1.400 a R$ 1.700, 
# tornando a comparação visual muito mais precisa e justa.
#O canal Booking.com lidera o ticket médio entre os canais conhecidos (aproximadamente R$ 1.735,83), 
# seguido de perto pela Expedia (R$ 1.648,93). O menor ticket médio vem do Site Próprio (R$ 1.475,80), 
# indicando uma excelente oportunidade para criar campanhas e pacotes que estimulem diárias de maior valor direto 
# na plataforma da rede.

In [ ]:
df_avaliacoes['nota_atendimento'] = pd.to_numeric(df_avaliacoes['nota_atendimento'], errors='coerce')
df_avaliacoes['nota_geral'] = pd.to_numeric(df_avaliacoes['nota_geral'], errors='coerce')

df_aval_limpo = df_avaliacoes.dropna(subset=['nota_atendimento', 'nota_geral'])
df_aval_limpo = df_aval_limpo[(df_aval_limpo['nota_atendimento'].between(0, 10)) & 
                              (df_aval_limpo['nota_geral'].between(0, 10))]

#calculo correlação
correlacao = df_aval_limpo['nota_atendimento'].corr(df_aval_limpo['nota_geral'])

#visualização com gráfico de dispersão e linha de tendência
plt.figure(figsize=(10, 6))
sns.scatterplot(data=df_aval_limpo, x='nota_atendimento', y='nota_geral', alpha=0.5, color='#8e44ad')
sns.regplot(data=df_aval_limpo, x='nota_atendimento', y='nota_geral', scatter=False, color='#2c3e50')

plt.title(f'Relação entre Atendimento e Satisfação Geral (Correlação: {correlacao:.3f})', fontsize=14, fontweight='bold', pad=15)
plt.xlabel('Nota de Atendimento')
plt.ylabel('Nota Geral de Satisfação')
sns.despine()
plt.show()

#A correlação resultou em aproximadamente -0.06. Como o valor está extremamente próximo de zero, 
# isso prova matematicamente que não há uma relação linear entre a nota de atendimento e a satisfação geral 
# neste banco de dados. Um hóspede pode dar nota 10 para o atendimento, mas dar nota 4 para a experiência geral 
# (talvez por problemas na estrutura, barulho ou localização).

In [ ]:
#filtrando apenas as reservas overbooking
df_overbooking = df_reservas_total[df_reservas_total['status_reserva'] == 'Overbooking'].copy()

#criando a coluna de mes/ano para identificar o período
df_overbooking['mes_ano'] = df_overbooking['data_checkin'].dt.to_period('M').astype(str)

#cruzando com o cadastro de hotéis para pegar o nome correto
df_over_completo = df_overbooking.merge(df_hoteis, on='id_hotel', how='left')

#agrupando por hotel para ver onde é mais crítico
over_por_hotel = df_over_completo['nome_hotel'].value_counts()

#agrupando por período para ver quando é mais crítico
over_por_periodo = df_over_completo['mes_ano'].value_counts().sort_index()

#figuras
fig, axes = plt.subplots(1, 2, figsize=(15, 5))

#hoteis
sns.barplot(x=over_por_hotel.values, y=over_por_hotel.index, ax=axes[0], palette='Reds_r')
axes[0].set_title('Casos de Overbooking por Unidade', fontweight='bold')

#período
axes[1].plot(over_por_periodo.index, over_por_periodo.values, marker='o', color='#c0392b', linewidth=2)
axes[1].set_title('Evolução dos Casos de Overbooking no Tempo', fontweight='bold')
axes[1].tick_params(axis='x', rotation=45)

plt.tight_layout()
sns.despine()
plt.show()

#O Nara Recife lidera o ranking de criticidade de Overbooking, registrando a maior parte dos incidentes do período. 
#Historicamente falando, esses picos costumam se concentrar em períodos de alta temporada (como dezembro e março).